export const BANKS_LIST = [
    { title: "VietinBank - Ngân Hàng TMCP Công Thương Việt Nam", value: "970415" },
    { title: "Public Bank - Ngân hàng TNHH MTV Public Việt Nam", value: "970439" },
    { title: "Techcombank - Ngân hàng TMCP Kỹ Thương Việt Nam", value: "970407" },
    { title: "Vietcombank - Ngân hàng TMCP Ngoại Thương Việt Nam", value: "970436" },
    { title: "VPBank - Ngân hàng TMCP Việt Nam Thịnh Vượng", value: "546034" },
    { title: "MB - Ngân Hàng TMCP Quân đội", value: "970422" },
    { title: "BIDV - Ngân hàng TMCP phát triển và đầu tư Việt Nam", value: "970418" },
    { title: "Sacombank - Ngân hàng TMCP Sài Gòn Thương Tín", value: "970403" },
    { title: "ACB - Ngân hàng TMCP Á Châu", value: "970416" },
    { title: "Agribank - Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam", value: "970405" },
    { title: "OCB - Ngân hàng TMCP Phương Đông", value: "970448" },
    { title: "ABBANK - Ngân hàng TMCP An Bình", value: "970425" },
    { title: "BaoVietBank - Ngân hàng TMCP Bảo Việt", value: "970438" },
    { title: "BacABank - Ngân hàng TMCP Bắc Á", value: "970409" },
    { title: "PVcombank - Ngân hàng TMCP Đại chúng", value: "970412" },
    { title: "Đông Á Bank - Ngân hàng TMCP Đông Á", value: "970406" },
    { title: "SeABank - Ngân hàng TMCP Đông Nam Á", value: "970440" },
    { title: "MSB - Ngân hàng TMCP Hàng hải Việt Nam", value: "970426" },
    { title: "SHBank - Ngân hàng TMCP Sài Gòn - Hà Nội", value: "970443" },
    { title: "KienLongBank - Ngân hàng TMCP Kiên Long", value: "970449" },
    { title: "HDBank - Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh", value: "970437" },
    { title: "NCB - Ngân hàng TMCP Quốc Dân", value: "970419" },
    { title: "VIBBank - Ngân hàng TMCP Quốc tế Việt Nam", value: "970441" },
    { title: "SCB - Ngân hàng TMCP Sài Gòn", value: "970429" },
    { title: "SGB - Ngân hàng TMCP Sài Gòn Công Thương", value: "970400" },
    { title: "VietABank - Ngân hàng TMCP Việt Á", value: "970427" },
    { title: "Eximbank - Ngân hàng TMCP Xuất Nhập khẩu Việt Nam", value: "970431" },
    { title: "LienVietPostBank - Ngân Hàng TMCP Bưu điện Liên Việt", value: "970446" },
    { title: "Petrolimex Group Bank - Ngân hàng TMCP Xăng Dầu Petrolimex", value: "970430" },
    { title: "Citi Bank - Ngân hàng Citi Bank Việt Nam", value: "533948" },
    { title: "TP Bank - Ngân hàng TMCP Tiên Phong", value: "970423" },
    { title: "Shinhan Bank - Ngân hàng TNHH MTV Shinhan", value: "970424" },
    { title: "VIB - Ngân hàng TMCP Quốc Tế Việt Nam", value: "970441" },
    { title: "VPBank - Ngân hàng TMCP Việt Nam phát triển thịnh vượng", value: "970432" },
    { title: "VietCapitalBank - Ngân hàng TMCP Bản Việt", value: "970454" },
    { title: "Nam A Bank - Ngân hàng TMCP Nam Á", value: "970428" }
  ];