export default {

    AUTH_LOGIN: 'login',
    AUTH_LOGIN_GOOGLE: 'auth/google',
    AUTH_LOGOUT: 'logout',
    AUTH_FULL_INFO: 'user',
    AUTH_FULL_INFO_V2: 'v2/user/info',
    AUTH_FULL_INFO_UPDATE: 'user/update',
    AUTH_FULL_INFO_UPDATE_V2: 'v2/user/update',
    AUTH_CITIZEN_ID_UPDATE: 'user/update/citizenid',
    AUTH_REGISTER: 'register',
    AUTH_REGISTER_V2: 'v2/register',
    AUTH_COMPANY_REGISTER: 'company-register',
    AUTH_FORGOT_PASSWORD: 'password/reset',
    AUTH_CHANGE_PASSWORD: 'password/change-password',
    AUTH_VERIFY_EMAIL: 'user/verify-email',
    AUTH_VERIFY_EMAIL_RESEND: 'user/verify-email/resend',
    AUTH_VERIFY_OTP: 'v2/verify-otp',
    AUTH_VERIFY_OTP_RESEND: 'v2/resend-otp',

    USER_LIST: 'user/list',

    HOME_INIT: 'pages/page/home',
    HOME_INIT_V2: '/web/v2/common/page/home',
    SETTING_INIT: '/web/v2/common/page/setting-info',
    SETTING_INIT_V2: '/web/v2/common/page/setting',

    INTRODUCE: 'pages/page/introduce',
    HOME_SUGGESTIONS: '/home/search/suggest',

    TEMPLATE_INIT: 'pages/page/template',
    TEMPLATE_FULL_INFO: 'templates/:templateId',
    TEMPLATE_PREVIEW: 'template/preview',
    TEMPLATE_LIST: 'templates',
    TEMPLATE_REACT: 'templates/react/:templateId',
    TEMPLATE_DOWNLOAD: 'template/download',
    TEMPLATE_SAVE_AS_TEMPLATE: 'templates/:templateId/template',
    TEMPLATE_SAVE_AS_DOCUMENT: 'templates/:templateId/document',
    
    DOCUMENT_LIST: 'documents',
    DOCUMENT_FULL_INFO: 'documents/:documentId',
    DOCUMENT_DELETE: 'documents/:documentId',
    DOCUMENT_UPDATE: 'documents/:documentId',
    DOCUMENT_UPLOAD: 'document/upload',
    DOCUMENT_SHARE: 'documents/share/:documentId',
    DOCUMENT_SHARE_LIST: 'documents/share/list',
    DOCUMENT_APPROVE_SHARE: 'documents/share/approve/:documentShareId',
    DOCUMENT_REJECT_SHARE: 'documents/share/reject/:documentShareId',
    DOCUMENT_CANCEL_SHARE: 'documents/share/cancel/:documentShareId',
    DOCUMENT_COMMENTS_LIST: 'documents/share/comments/:documentId',
    DOCUMENT_CREATE_COMMENT: 'documents/share/comment/:documentId',
    DOCUMENT_COMMENT: 'documents/share/comment/:commentId',
    DOCUMENT_PREVIEW_SHARE: 'preview/share-document/:documentShareId',

    JOB_INIT: 'pages/page/jobs',
    JOB_SUGGESTIONS: '/projects/search/suggest',
    POST_INIT: 'posts',
    POST_FULL_INFO: 'posts/:postId',

    JOB_DETAIL: 'projects/:jobId',
    JOB_DETAIL_V2: '/web/v2/projects/:jobId',

    JOB_SELECTBOX_FOR_ADD: 'projects/create/new',
    JOB_ADD: 'projects',
    JOB_ADD_V2: "web/v2/projects",
    JOB_EDIT: 'projects/:jobId',
    JOB_REACTION: 'projects/react/:jobId',
    JOB_APPLY: 'projects/partner/apply/:jobId',
    JOB_UPLOAD_DOCUMENT: 'projects/partner/upload-document/:jobId',
    JOB_UPDATE_DOCUMENT: 'projects/partner/document/update/:resultId',
    JOB_DOWNLOAD_DOCUMENT: 'download/document/:resultId',
    JOB_DELETE_DOCUMENT: 'projects/result/:resultId',
    JOB_SEND_RESULT: 'projects/result/complete/:jobId',
    JOB_AGREE_RESULT: 'projects/result/approve/:jobId',
    JOB_PARTNER_RATE: 'projects/result/rate/:jobId',
    JOB_REJECT_RESULT: 'projects/result/reject/:jobId',
    JOB_DELETE: 'projects/:jobId',
    JOB_SEND_OFFER: 'projects/deal/:jobId',
    JOB_CONFIRM_OFFER: 'projects/confirm/:jobId',
    JOB_PLATFORM_FEE: 'projects/platformfee',
    JOB_CONFIRM_BID: 'projects/partner/confirm-bid/:jobId',
    JOB_FAVORITE_LIST: 'projects/favorite',

    PARTNER_INIT: 'pages/page/partners',
    PARTNER_LIST: 'partners',
    PARTNER_LIST_V3: 'web/v2/partners',
    PARTNER_LIST_V2: 'v2/partners',
    PARTNER_FULL_INFO: 'partners/:partnerId',
    PARTNER_FULL_INFO_V2: '/web/v2/partners/:partnerId',
    PARTNER_SELECT_BOX: 'partner/create',
    PARTNER_CONNECT: 'partners/connect',
    PARTNER_REVIEWS: 'user-reviews/:partnerId',
    PARTNER_REACT: 'partners/favorite/:partnerId',
    PARTNER_FAVORITE_LIST: 'partners/favorite',
    PARTNER_COMPLAIN: 'partners/complain',

    NOTIFICATIONS_LIST: 'notifications',
    NOTIFICATION_DETAIL: 'notifications/:notificationId',
    NOTIFICATION_UPDATE: 'notifications/update',

    PAYMENT_PREPAY: 'transactions/prepay',
    PAYMENT_CONFIRM: 'transactions/confirmpay',
    TRANSACTION_LIST: 'transactions',
    TRANSACTION_FULL_INFO: 'transactions/:transactionId',
    TRANSACTION_FULL_INFO_DETAIL: "customer/wallet/transactions/:transactionId",
    PRICING: 'pages/page/service',
    ALL_USER_SUSPEND: 'user/service/cancel',
    CHECK_CITIZEN_ID_STATUS: 'user/check/citizenid',

    TERM_OF_USE: 'terms-of-use',
    PRIVACY_POLICY: 'privacy-policy',

    CONTRACT_LIST: 'user/contract',
    CONTRACT_FULL_INFO: 'user/contract/:contractId',

    CONTRACT_SAVE: 'user/contract',
    CONTRACT_UPDATE: 'user/contract/:contractId',
    CONTRACT_UPDATE_PDF: 'user/contract/pdf/:contractId',
    CONTRACT_UPDATE_SIGN: 'user/contract/sign/config/:contractId',
    CONTRACT_CANCEL: 'user/contract/cancel/:contractId',
    CONTRACT_DELETE: 'user/contract/:contractId',

    CONTRACT_REQUEST_MAIL_TO_SIGN: 'user/contract/sign/send-mail/:contractId',
    CONTRACT_CONFIRM_MAIL_SIGN: 'user/contract/sign/confirm/:code',
    CONTRACT_REQUEST_SIGN_ON_MYSIGN: 'user/contract/sign/request-mySign/:contractId',
    CONTRACT_CHECK_SIGN_ON_MYSIGN: 'user/contract/sign/check-transaction/:signId',
    CONTRACT_RESEND_SIGN_REQUEST: 'user/contract/sign/resign',
    CONTRACT_CHECK_MY_SIGN_ID: 'contract/sign/mysigninfo',

    CONTRACT_SIGN_ADD: 'user/contract/add/:contractId',
    CONTRACT_SIGN_DELETE: 'user/contract/sign/:signId',

    CHAT_ROOM_LIST: 'v2/rooms/list/chat/:userId',
    CHAT_ROOM_DETAIL: 'v2/rooms/list/chat/:roomId',
    MESSAGE_LIST: 'v2/rooms/chats',
    MESSAGE_SEND: 'v2/rooms/:roomId/message',
    MESSAGE_REPLY: 'v2/rooms/chat/:roomId/message/:messId/page',
    FILE_CHAT: "v2/rooms/chat/:roomId/attachment",

    UPLOAD_FILES_OF_TYPICAL_PROJECTS: 'partners/typical/upload/attachment',
    UPLOAD_IMAGE_OF_TYPICAL_PROJECTS: 'partners/typical/upload/image',
    DELETE_FILES_OF_TYPICAL_PROJECTS: 'partners/typical/file/delete',
    BANK: '/banks',
};
